### ISSUE TITLE
Invalid python auth example

### ISSUE THREAD

**Issue by Danipulok** [whitebit-exchange/api-quickstart#14]
Current nonce generation in [python](https://github.com/whitebit-exchange/api-quickstart/blob/6e2b2b14f7dffc47615544f43c1eb66b51c3fb96/src/python/auth.py#L14) is not valid and returns:
```
{
    "code": 0,
    "message": "Your nonce is more than 5 seconds lesser than the current nonce."
}
```
This happens because `str(int(time.time()))` generates current epoch time in **seconds**, and we need to pass nonce in **milliseconds**, as specified [here](https://github.com/whitebit-exchange/api-docs/blame/main/docs/Private/http-auth.md#L22).

I propose to accept [this PR](https://github.com/whitebit-exchange/api-quickstart/pull/13) to fix this.

**Comment by john-whitebit** [comment]
Hello Danipulok!
Thank you for PR! 👍🏻
